% block_inventory.m
% Lists the library paths of the Simscape blocks the BeltTwin PMSM model will use,
% so the model-building scripts can use the exact paths of this MATLAB release.
% Usage: run in MATLAB, copy the whole output.

names = { ...
    'PMSM', ...
    'Average-Value Inverter', ...
    'Park Transform', ...
    'Inverse Park Transform', ...
    'Clarke Transform', ...
    'Inverse Clarke Transform', ...
    'PMSM Current Controller', ...
    'PMSM Field-Oriented Control', ...
    'Thermal Mass', ...
    'Convective Heat Transfer', ...
    'Temperature Source', ...
    'Inertia', ...
    'Rotational Friction', ...
    'Ideal Torque Source', ...
    'Ideal Angular Velocity Source', ...
    'Ideal Rotational Motion Sensor', ...
    'Solver Configuration', ...
    'DC Voltage Source', ...
    'Electrical Reference', ...
    'Mechanical Rotational Reference', ...
    'Belt Pulley', ...
    'Simple Gear', ...
    'Current Sensor (Three-Phase)', ...
    'Simulink-PS Converter', ...
    'PS-Simulink Converter'};

libs = {'ee_lib', 'fl_lib', 'sdl_lib', 'nesl_utility'};
loaded = {};
for i = 1:numel(libs)
    try
        load_system(libs{i});
        loaded{end+1} = libs{i}; %#ok<AGROW>
    catch err
        fprintf('LIBRARY NOT LOADED: %s (%s)\n', libs{i}, err.message);
    end
end

fprintf('\nMATLAB %s\n\n', version);
for n = 1:numel(names)
    hits = {};
    for i = 1:numel(loaded)
        try
            h = find_system(loaded{i}, 'LookUnderMasks', 'all', 'FollowLinks', 'on', ...
                'MatchFilter', @Simulink.match.allVariants, 'Name', names{n});
        catch
            h = find_system(loaded{i}, 'LookUnderMasks', 'all', 'FollowLinks', 'on', ...
                'Name', names{n});
        end
        hits = [hits; h(:)]; %#ok<AGROW>
    end
    if isempty(hits)
        fprintf('%-34s NOT FOUND\n', names{n});
    else
        fprintf('%-34s %s\n', names{n}, strjoin(hits', '  |  '));
    end
end
